// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: internal/protobuf/vouchergrpc/voucher_grpc.proto

package vouchergrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UseVoucherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId  string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Vouchers []string `protobuf:"bytes,2,rep,name=vouchers,proto3" json:"vouchers,omitempty"`
}

func (x *UseVoucherRequest) Reset() {
	*x = UseVoucherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_vouchergrpc_voucher_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseVoucherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseVoucherRequest) ProtoMessage() {}

func (x *UseVoucherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_vouchergrpc_voucher_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseVoucherRequest.ProtoReflect.Descriptor instead.
func (*UseVoucherRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_vouchergrpc_voucher_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *UseVoucherRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UseVoucherRequest) GetVouchers() []string {
	if x != nil {
		return x.Vouchers
	}
	return nil
}

type VoucherRespDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VoucherRespDetail) Reset() {
	*x = VoucherRespDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_vouchergrpc_voucher_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoucherRespDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoucherRespDetail) ProtoMessage() {}

func (x *VoucherRespDetail) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_vouchergrpc_voucher_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoucherRespDetail.ProtoReflect.Descriptor instead.
func (*VoucherRespDetail) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_vouchergrpc_voucher_grpc_proto_rawDescGZIP(), []int{1}
}

type CheckingVoucherResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool                 `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	Items     []*VoucherRespDetail `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CheckingVoucherResponse) Reset() {
	*x = CheckingVoucherResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_vouchergrpc_voucher_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckingVoucherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckingVoucherResponse) ProtoMessage() {}

func (x *CheckingVoucherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_vouchergrpc_voucher_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckingVoucherResponse.ProtoReflect.Descriptor instead.
func (*CheckingVoucherResponse) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_vouchergrpc_voucher_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *CheckingVoucherResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *CheckingVoucherResponse) GetItems() []*VoucherRespDetail {
	if x != nil {
		return x.Items
	}
	return nil
}

type ApplyVoucherResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
}

func (x *ApplyVoucherResponse) Reset() {
	*x = ApplyVoucherResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_vouchergrpc_voucher_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyVoucherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyVoucherResponse) ProtoMessage() {}

func (x *ApplyVoucherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_vouchergrpc_voucher_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyVoucherResponse.ProtoReflect.Descriptor instead.
func (*ApplyVoucherResponse) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_vouchergrpc_voucher_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyVoucherResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type CheckingVoucherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vouchers         []string `protobuf:"bytes,1,rep,name=vouchers,proto3" json:"vouchers,omitempty"`
	OrderTotalAmount int32    `protobuf:"varint,2,opt,name=order_total_amount,json=orderTotalAmount,proto3" json:"order_total_amount,omitempty"`
	PaymentMethod    int32    `protobuf:"varint,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	UserId           string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CheckingVoucherRequest) Reset() {
	*x = CheckingVoucherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_vouchergrpc_voucher_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckingVoucherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckingVoucherRequest) ProtoMessage() {}

func (x *CheckingVoucherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_vouchergrpc_voucher_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckingVoucherRequest.ProtoReflect.Descriptor instead.
func (*CheckingVoucherRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_vouchergrpc_voucher_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *CheckingVoucherRequest) GetVouchers() []string {
	if x != nil {
		return x.Vouchers
	}
	return nil
}

func (x *CheckingVoucherRequest) GetOrderTotalAmount() int32 {
	if x != nil {
		return x.OrderTotalAmount
	}
	return 0
}

func (x *CheckingVoucherRequest) GetPaymentMethod() int32 {
	if x != nil {
		return x.PaymentMethod
	}
	return 0
}

func (x *CheckingVoucherRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_internal_protobuf_vouchergrpc_voucher_grpc_proto protoreflect.FileDescriptor

var file_internal_protobuf_vouchergrpc_voucher_grpc_proto_rawDesc = []byte{
	0x0a, 0x30, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x73, 0x22, 0x13,
	0x0a, 0x11, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x22, 0x62, 0x0a, 0x17, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x56,
	0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x28, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x56,
	0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x35, 0x0a, 0x14, 0x41, 0x70, 0x70, 0x6c, 0x79,
	0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0xa2,
	0x01, 0x0a, 0x16, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x56, 0x6f, 0x75, 0x63, 0x68,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x6f, 0x75,
	0x63, 0x68, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x76, 0x6f, 0x75,
	0x63, 0x68, 0x65, 0x72, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x10, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x32, 0x99, 0x01, 0x0a, 0x12, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x52, 0x50, 0x43, 0x12, 0x46, 0x0a, 0x0f, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x12, 0x17, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e,
	0x67, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0c, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x56, 0x6f, 0x75, 0x63, 0x68,
	0x65, 0x72, 0x12, 0x12, 0x2e, 0x55, 0x73, 0x65, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x56, 0x6f,
	0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x0e, 0x5a, 0x0c, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_protobuf_vouchergrpc_voucher_grpc_proto_rawDescOnce sync.Once
	file_internal_protobuf_vouchergrpc_voucher_grpc_proto_rawDescData = file_internal_protobuf_vouchergrpc_voucher_grpc_proto_rawDesc
)

func file_internal_protobuf_vouchergrpc_voucher_grpc_proto_rawDescGZIP() []byte {
	file_internal_protobuf_vouchergrpc_voucher_grpc_proto_rawDescOnce.Do(func() {
		file_internal_protobuf_vouchergrpc_voucher_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protobuf_vouchergrpc_voucher_grpc_proto_rawDescData)
	})
	return file_internal_protobuf_vouchergrpc_voucher_grpc_proto_rawDescData
}

var file_internal_protobuf_vouchergrpc_voucher_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_protobuf_vouchergrpc_voucher_grpc_proto_goTypes = []interface{}{
	(*UseVoucherRequest)(nil),       // 0: UseVoucherRequest
	(*VoucherRespDetail)(nil),       // 1: VoucherRespDetail
	(*CheckingVoucherResponse)(nil), // 2: CheckingVoucherResponse
	(*ApplyVoucherResponse)(nil),    // 3: ApplyVoucherResponse
	(*CheckingVoucherRequest)(nil),  // 4: CheckingVoucherRequest
}
var file_internal_protobuf_vouchergrpc_voucher_grpc_proto_depIdxs = []int32{
	1, // 0: CheckingVoucherResponse.items:type_name -> VoucherRespDetail
	4, // 1: VoucherServiceGRPC.CheckingVoucher:input_type -> CheckingVoucherRequest
	0, // 2: VoucherServiceGRPC.ApplyVoucher:input_type -> UseVoucherRequest
	2, // 3: VoucherServiceGRPC.CheckingVoucher:output_type -> CheckingVoucherResponse
	3, // 4: VoucherServiceGRPC.ApplyVoucher:output_type -> ApplyVoucherResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_protobuf_vouchergrpc_voucher_grpc_proto_init() }
func file_internal_protobuf_vouchergrpc_voucher_grpc_proto_init() {
	if File_internal_protobuf_vouchergrpc_voucher_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_protobuf_vouchergrpc_voucher_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseVoucherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_vouchergrpc_voucher_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoucherRespDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_vouchergrpc_voucher_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckingVoucherResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_vouchergrpc_voucher_grpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyVoucherResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_vouchergrpc_voucher_grpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckingVoucherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protobuf_vouchergrpc_voucher_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protobuf_vouchergrpc_voucher_grpc_proto_goTypes,
		DependencyIndexes: file_internal_protobuf_vouchergrpc_voucher_grpc_proto_depIdxs,
		MessageInfos:      file_internal_protobuf_vouchergrpc_voucher_grpc_proto_msgTypes,
	}.Build()
	File_internal_protobuf_vouchergrpc_voucher_grpc_proto = out.File
	file_internal_protobuf_vouchergrpc_voucher_grpc_proto_rawDesc = nil
	file_internal_protobuf_vouchergrpc_voucher_grpc_proto_goTypes = nil
	file_internal_protobuf_vouchergrpc_voucher_grpc_proto_depIdxs = nil
}
