package entities

const (
	FREE_SHIP        = 1
	PAYMENT_DISCOUNT = 2
	STORE_DISCOUNT   = 3

	PENDING  = 0
	ACTIVE   = 1
	INACTIVE = -1

	VOUCHER_APPLY_SUCCESS = 1
	VOUCHER_APPLY_FAILED  = -1

	FIXED_DISCOUNT   = 0
	PERCENT_DISCOUNT = 1

	COD_METHOD = 1
)

const (
	STORE_MAX_VC_COUNTS_POLICY      = 1000
	STORE_MAX_FIXED_VALUE_POLICY    = 1000000 //100.000VNĐ
	STORE_MAX_PERCENT_POLICY        = 0.15
	STORE_MAX_CREATED_COUNTS_POLICY = 5
)
